### ISSUE TITLE
Action log

### ISSUE THREAD

**Issue by NinoDoko** [VapourApps/va_master#12]
There should be a logging system which logs user calls to the api. This system should not log GET requests, and should be readily available for parsing so it can be viewed in the dashboard.

**Comment by ljupcovangelski** [comment]
The action log should be logged through the local syslog (rsyslog), into the /var/log/vapourapps/va-master logfile, with [INFO] level.

**Comment by NinoDoko** [comment]
Messages are correctly logged to vapourapps.log and sent to frontend when needed.
