### ISSUE TITLE
Create syslog to va-master hook

### ISSUE THREAD

**Issue by ljupcovangelski** [VapourApps/va_master#15]
We must configure the va-master to be a central syslog server, for critical logs/events, including activity from/to the va-master API. 

@markododa We should add into the image that the folder /var/log/vapourapps is created. The syslog should be configured so that it accepts logs from remote hosts and writes log files, coming from a certain host, into /var/log/vapourapps/{hostname}. {hostname} should be the {instancename}, retrieved from consul.

@NinoDoko should make va-master hook to the syslog so that the va-master API can retrieve X nubmer of log entries from a particular logfile or from all of the files in /var/log/vapourapps. Those entries will be returned to the frontend when requested through the API.

**Comment by NinoDoko** [comment]
There is now a url endpoint for getting the log - /log. This will open a websocket which will transfer existing messages as well as new log messages as they appear.

**Comment by NinoDoko** [comment]
The log as well as the websocket are now working properly.
