### ISSUE TITLE
Billing info for Hosts

### ISSUE THREAD

**Issue by ljupcovangelski** [VapourApps/va_master#25]
We need to create functions, in the drivers for different host types, for retrieving billing data from the Hosts.

Billing data should include:
* current monthly billing (from 1st of the month, to the present date)
* estimated monthly billing (estimated sum, retrieved from the API if possible)
* billing in a time period (retrieve information about usage in period "from_date" to "to_date")

For CL, AWS, GCP biling data will be available, while for OpenStack, VMWare and Libvirt there is only usage. For the later three, only the third functionality will be enabled, for retrieving usage information.

**Comment by NinoDoko** [comment]
This works for CLC, other drivers return default values.
