### ISSUE TITLE
VPN Installation/configuration on backend

### ISSUE THREAD

**Issue by ljupcovangelski** [VapourApps/va_master#8]
Installation:
1. On vapourapps init ask two values:
* Hosts VPN Endpoint [vpn.{domain}]: (This should be accessible from Hosts/apps)
* Company name: (Name of the Company, to be used in VPN Certificates)
2. Write those values into pilars file
3. Run state for VPN on local va-master

Configuration:
1. Port module from old Dashboard
2. Communicate with new Dashboard

**Comment by NinoDoko** [comment]
VPN info is added to the pillars and saved in store. Just needs testing with the state.

**Comment by NinoDoko** [comment]
VPN is successfully started on vapourapps init.

**Comment by ljupcovangelski** [comment]
For frontend functionality to be completed, the following functions need to be provided by the va-master API:
* Add user
* Download certificate
* Revoke user
* List logins

**Comment by NinoDoko** [comment]
Everything seems to be working properly.
